apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: paperwork-gateway-deployment
  labels:
    app: paperwork-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paperwork-gateway
  template:
    metadata:
      labels:
        app: paperwork-gateway
    spec:
      containers:
        - name: paperwork-gateway
          image: registry-vpc.cn-beijing.aliyuncs.com/easyassess/paperwork-gateway:latest
          ports:
            - containerPort: 5100
              name: gateway
            - containerPort: 5000
              name: admin

---

apiVersion: v1
kind: Service
metadata:
  name: paperwork-gateway-svc
#  annotations:
#    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-2zeqwbkqh1p8ma311dfwl
  labels:
    app: paperwork-gateway
spec:
  selector:
    app: paperwork-gateway
  ports:
    - protocol: TCP
      name: gateway
      port: 5100
      targetPort: 5100
    - protocol: TCP
      name: admin
      port: 5000
      targetPort: 5000
  type: LoadBalancer
