admin:
  protocol: http
  port: 8280
gateway:
  protocol: http
  port: 8180
servicesEndpoints:
  paperwork:
    url: 'http://localhost:5000'
  admin:
    url: 'http://localhost:8280'
gatewayEndpoints:
  admin:
    paths:
      - '/admin/*'
    proxy:
      validate:
        authentication:
          enabled: true
        authorization:
          enabled: true
      forward:
        serviceEndpoint: admin
        changeOrigin: true
        prependPath:  true
        ignorePath:   false
        stripPath:    true
  paperwork:
    paths:
      - '/paper-service/*'
      - '/paper-data-service/*'
    proxy:
      validate:
        authentication:
          enabled: true
        authorization:
          enabled: true
      forward:
        serviceEndpoint: paperwork
        changeOrigin: true
        prependPath:  true
        ignorePath:   false
        stripPath:    true
