admin:
  protocol: http
  port: 8280
gateway:
  protocol: http
  port: 8180
middlewares:
  body-parser:
  authentication:
    url: 'mongodb://localhost:27017'
    username:
    password:
  authorization:
endpoints:
  login:
    paths:
      - '/auth/token'
    proxy:
      forward:
        url: 'http://localhost:8280'
        stripPath: false
  admin:
    paths:
      - '/admin/*'
    proxy:
      forward:
        url: 'http://localhost:8280'
        stripPath: true
      additionalProps:
        authorization: true
        authentication: true
  paperwork:
    paths:
      - '/paper-service/*'
      - '/paper-data-service/*'
    proxy:
      forward:
        url: 'http://localhost:5000'
        stripPath: true
      additionalProps:
        authorization: true
        authentication: true
