http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/paper-service/*'
serviceEndpoints:
  paperworkService:
    url: 'http://localhost:5000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
        - action:
            serviceEndpoint: paperworkService
            changeOrigin: true
            prependPath:  true
            ignorePath:   false
            stripPath:    true
